language: node_js

node_js:
  - "lts/*"

cache:
  yarn: true
  directories:
    - node_modules

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

#before_install:
#  - export CHROME_BIN=chromium-browser
#  - export DISPLAY=:99.0
#  - sh -e /etc/init.d/xvfb start
#
script:
  - yarn --version
  - yarn check --integrity
  - yarn install
  - yarn build
  - yarn lint
  - yarn test
  - yarn test:coverage
  - yarn test:routes
  - yarn test:a11y
after_success:
  - yarn test:codacy-upload
  - yarn test:codecov-upload
