version: '3'

services:
    jui-webapp:
        build:
            context: .
        image: hmcts/jui-webapp:latest
        environment:
        - NODE_ENV=development
        - PORT=8080
        - JUI_ENV = "docker"
        - REFORM_SERVICE_NAME = "jui-webapp"
        - REFORM_TEAM = "jui"
        - REFORM_SERVICE_TYPE = "node"
        - REFORM_ENVIRONMENT = "docker"
        - PACKAGES_NAME = "jui-webapp"
        - PACKAGES_PROJECT = "jui"
        - PACKAGES_ENVIRONMENT = "docker"
        - S2S_SECRET = "AAAAAAAAAAAAAAAA"
        - IDAM_SECRET = "AAAAAAAAAAAAAAAA"
        ports:
        - 3000:8080




