version: '2.1'

services:
#  ccd-case-management-web:
#    image: "docker.artifactory.reform.hmcts.net/ccd/ccd-case-management-web:${BRANCH:-master}"
#    container_name: ccd-case-management-web
#    environment:
#      IDAM_LOGIN_URL: https://localhost:3501/login
#      CCD_GATEWAY_BASE_URL: http://localhost:3453
#      CCD_ACTIVITY_BASE_URL:
#      DM_GATEWAY_BASE_URL: https://api-gateway.dev.dm.reform.hmcts.net
#      OAUTH2_CLIENT_ID: ccd_gateway
#    ports:
#      - 3451:80
#    depends_on:
#      - ccd-api-gateway
#
#  ccd-api-gateway:
#    image: "docker.artifactory.reform.hmcts.net/ccd/ccd-api-gateway:${BRANCH:-master}"
#    container_name: ccd-api-gateway
#    environment:
#      IDAM_LOGOUT_URL: https://localhost:3501/login/logout
#      IDAM_BASE_URL: http://idam-api:8080
#      IDAM_USER_URL: http://idam-api:8080
#      IDAM_S2S_URL: http://service-auth-provider-app:8489
#      IDAM_SERVICE_KEY: AAAAAAAAAAAAAAAA
#      IDAM_OAUTH2_CLIENT_ID: ccd_gateway
#      IDAM_OAUTH2_CLIENT_SECRET: "${OAUTH2_CLIENT_CCD_GATEWAY}"
#      IDAM_OAUTH2_TOKEN_ENDPOINT: http://idam-api:8080/oauth2/token
#      PROXY_AGGREGATED: http://ccd-data-store-api:4452
#      PROXY_DATA: http://ccd-data-store-api:4452
#      PROXY_DEFINITION_IMPORT: http://ccd-definition-store-api:4451
#      PROXY_DEFINITION_DATA: http://ccd-definition-store-api:4451/api/data
#      PROXY_DEFINITION_DISPLAY: http://ccd-definition-store-api:4451/api/display
#      APPINSIGHTS_INSTRUMENTATIONKEY: key
#    ports:
#      - 3453:3453
#    depends_on:
#      - ccd-user-profile-api
#      - ccd-definition-store-api
#      - ccd-data-store-api

  ccd-user-profile-api:
    image: "docker.artifactory.reform.hmcts.net/ccd/ccd-user-profile-api:${BRANCH:-master}"
    environment:
      USER_PROFILE_DB_HOST: ccd-user-profile-database
      USER_PROFILE_DB_PORT: 5432
      USER_PROFILE_DB_USERNAME:
      USER_PROFILE_DB_PASSWORD:
      USER_PROFILE_DB_USE_SSL:
      USER_PROFILE_S2S_AUTHORISED_SERVICES: ccd_data,ccd_definition
      IDAM_S2S_URL: http://service-auth-provider-app:8489
      REFORM_SERVICE_NAME: ccd-user-profile-api
      REFORM_TEAM: ccd
      REFORM_ENVIRONMENT: local
      APPINSIGHTS_INSTRUMENTATIONKEY: key
    ports:
      - 4453:4453
    depends_on:
      - ccd-user-profile-database
    links:
      - ccd-user-profile-database
      - service-auth-provider-app

  ccd-user-profile-database:
    image: "docker.artifactory.reform.hmcts.net/ccd/ccd-user-profile-database:${BRANCH:-master}"
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      USER_PROFILE_DB_USERNAME:
      USER_PROFILE_DB_PASSWORD:
    ports:
      - 5453:5432
    volumes:
      - ccd-user-profile-database-data:/var/lib/postgresql/data

  ccd-definition-store-api:
    image: "docker.artifactory.reform.hmcts.net/ccd/ccd-definition-store-api:${BRANCH:-master}"
    environment:
      DEFINITION_STORE_DB_HOST: ccd-definition-store-database
      DEFINITION_STORE_DB_PORT: 5432
      DEFINITION_STORE_DB_USERNAME:
      DEFINITION_STORE_DB_PASSWORD:
      DEFINITION_STORE_DB_USE_SSL:
      DEFINITION_STORE_IDAM_KEY: AAAAAAAAAAAAAAAA
      DEFINITION_STORE_S2S_AUTHORISED_SERVICES: ccd_data,ccd_gw,jui_webapp
      USER_PROFILE_HOST: http://ccd-user-profile-api:4453
      IDAM_USER_URL: http://idam-api:8080
      IDAM_S2S_URL: http://service-auth-provider-app:8489
      REFORM_SERVICE_NAME: ccd-definition-store-api
      REFORM_TEAM: ccd
      REFORM_ENVIRONMENT: local
      APPINSIGHTS_INSTRUMENTATIONKEY: key
    ports:
      - 4451:4451
    depends_on:
      - ccd-definition-store-database
      - ccd-user-profile-api
    links:
      - ccd-definition-store-database
      - ccd-user-profile-api
      - idam-api
      - service-auth-provider-app

  ccd-definition-store-database:
    image: "docker.artifactory.reform.hmcts.net/ccd/ccd-definition-store-database:${BRANCH:-master}"
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      DEFINITION_STORE_DB_USERNAME:
      DEFINITION_STORE_DB_PASSWORD:
    ports:
      - 5451:5432
    volumes:
      - ccd-definition-store-database-data:/var/lib/postgresql/data

  ccd-data-store-api:
    image: "docker.artifactory.reform.hmcts.net/ccd/ccd-data-store-api:${BRANCH:-master}"
    environment:
      DATA_STORE_DB_HOST: ccd-data-store-database
      DATA_STORE_DB_PORT: 5432
      DATA_STORE_DB_USERNAME:
      DATA_STORE_DB_PASSWORD:
      DATA_STORE_DB_USE_SSL:
      DATA_STORE_IDAM_KEY: AAAAAAAAAAAAAAAA
      DATA_STORE_TOKEN_SECRET: iuasbcuasdcbasdgcasdgcuysachjsacyasdgjcgasdj
      DATA_STORE_S2S_AUTHORISED_SERVICES: ccd_gw
      DEFINITION_STORE_HOST: http://ccd-definition-store-api:4451
      USER_PROFILE_HOST: http://ccd-user-profile-api:4453
      IDAM_USER_URL: http://idam-api:8080
      IDAM_S2S_URL: http://service-auth-provider-app:8489
      REFORM_SERVICE_NAME: ccd-data-store-api
      REFORM_TEAM: ccd
      REFORM_ENVIRONMENT: local
      APPINSIGHTS_INSTRUMENTATIONKEY: key
    ports:
      - 4452:4452
    depends_on:
      - ccd-data-store-database
      - ccd-user-profile-api
      - ccd-definition-store-api
    links:
      - ccd-data-store-database
      - ccd-user-profile-api
      - ccd-definition-store-api
      - idam-api
      - service-auth-provider-app

  ccd-data-store-database:
    image: "docker.artifactory.reform.hmcts.net/ccd/ccd-data-store-database:${BRANCH:-master}"
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      DATA_STORE_DB_USERNAME:
      DATA_STORE_DB_PASSWORD:
    ports:
      - 5452:5432
    volumes:
      - ccd-data-store-database-data:/var/lib/postgresql/data

volumes:
  ccd-user-profile-database-data:
  ccd-definition-store-database-data:
  ccd-data-store-database-data:
